name: ecommerce CI/CD Pipeline with VPS Deploy

on:
  push:
    branches: ["main"]

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PORT: ${{ secrets.SSH_PORT || '22' }}
  DEPLOY_PATH: ${{ secrets.VPS_DEPLOY_PATH }}
  PM2_APP_NAME: 'dulo'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Enable Go modules
        run: go mod tidy

      - name: Build Go binary
        run: go build -o build/dulo ./cmd/api

      - name: Archive build artifacts
        run: |
          mkdir -p artifact
          cp -r build/* artifact/
          echo "Artifacts contents:"
          ls -la artifact/

      - name: Upload artifacts for deploy
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifact

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts

      - name: Upload binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "artifact/*"
          target: "${{ env.DEPLOY_PATH }}/"
          strip_components: 1

      - name: Restart app on VPS
        run: |
          ssh -i ~/.ssh/deploy_key \
              -p $SSH_PORT \
              -o StrictHostKeyChecking=no \
              $SSH_USER@$SSH_HOST "
                cd $DEPLOY_PATH && \
                pkill -f dulo || true && \
                nohup ./dulo > dulo.log 2>&1 &
              "

      - name: Verify deployment
        run: |
          sleep 5
          ssh -i ~/.ssh/deploy_key \
              -p $SSH_PORT \
              -o StrictHostKeyChecking=no \
              $SSH_USER@$SSH_HOST "
                ps aux | grep instantpay || echo 'App may not be running'
              "

      - name: Success message
        run: |
          echo "DEPLOYMENT SUCCESSFUL!"
          echo "App is live at: http://$SSH_HOST"
